### PR TITLE
Update to 1.7.1, replace patches with flags

### PR DESCRIPTION
**Pull request by JMoerman**
1.6.8 has been outdated for quite some time, so lets update to something recent.

I've introduced a way to set the APP_ID with a cmake flag removing the need for `0001-Temporary-app-id-workaround.patch`.
`0002-Fix-and-update-appdata.patch` was also outdated and no longer in use, so this patch was removed as well.

Calling `gtk-update-icon-cache` doesn't seem to have any effect so I have added `-DICON_UPDATE=OFF` to config-opts. (Do tell me if I'm mistaken with this.)

Until a few hours ago I had no experience with flatpak package generation. Everything seems fine and the result seems fine.

One thing that did stand out is that the application was not translated when running using `flatpak-builder --run build/ de.manuel_kehl.go-for-it.yml de.manuel_kehl.go-for-it`, is this normal?
Do I need to set the locale somewhere when running flatpak applications?

### CODE REVIEW

**Comment by AsavarTzeth** [comment]
Oh, thank you! This was on my weekly todo list.

Could the locale issue be similar to this [issue](https://github.com/jangernert/FeedReader/issues/540)? That seems like a common mistake, since `/usr` is the usual installation prefix in which case it just works.

Since you are new to Flatpak it is worth mentioning that `/usr` is reserved by the runtime and read-only to the app. All application files are installed under `/app`.

Also, because you are the developer of this app you do have the right to claim this repository and get direct commit access. Would you be interested in this? I (and others) would still be around if you need help. See [the wiki](https://github.com/flathub/flathub/wiki/App-Submission#someone-else-has-put-my-app-on-flathubwhat-do-i-do) for more information.

**Comment by AsavarTzeth** [comment]
bot, build

**Comment by JMoerman** [comment]
> Could the locale issue be similar to this [issue](https://github.com/jangernert/FeedReader/issues/540)? That seems like a common mistake, since `/usr` is the usual installation prefix in which case it just works.

No that isn't the cause, as
```
$ cmake -DBUILD_TESTS=ON -DCMAKE_INSTALL_PREFIX=/home/jonathan/test/ -DAPP_ID=test.go-for-it .. 
$ make -j15
$ make install
$ '/home/jonathan/test/bin/test.go-for-it'
```
works fine. (Gettext package name depends on the app id and I haven't installed test.go-for-it system wide.)

I just tried the build by flathubbot and that build works fine so `flatpak-builder` must be doing something strange when running a local build.

> Since you are new to Flatpak it is worth mentioning that `/usr` is reserved by the runtime and read-only to the app. All application files are installed under `/app`.

_Go For It!_ uses `CMAKE_INSTALL_PREFIX` for its installation directory, it will happily install into whatever directory you tell it to.

> Also, because you are the developer of this app you do have the right to claim this repository and get direct commit access. Would you be interested in this? I (and others) would still be around if you need help. See [the wiki](https://github.com/flathub/flathub/wiki/App-Submission#someone-else-has-put-my-app-on-flathubwhat-do-i-do) for more information.

As I don't need another distro to build and test this and I do not need to write/understand autotool like scripts: Yes, you can make me maintainer of this repository. Having an extra target will also be useful in preventing and debugging issues.

**Comment by AsavarTzeth** [comment]
> I just tried the build by flathubbot and that build works fine so flatpak-builder must be doing something strange when running a local build.

Sorry, you are absolutely correct. This seems to be specific to `flatpak-builder`. It is indeed likely setting the environment up slightly differently, since it is mainly meant for building the app.

Personally I have only used `--run` to get a shell inside the build environment when I debug build failures.

Try this instead:

```
flatpak-builder --user --install build de.manuel_kehl.go-for-it.yml
flatpak run de.manuel_kehl.go-for-it//master
```

As for making you the maintainer; I'm sorry to say I don't have that power. You would have to contact a Flathub admin on the mailing list: flathub@lists.freedesktop.org.

**Comment by JMoerman** [comment]
> As for making you the maintainer; I'm sorry to say I don't have that power. You would have to contact a Flathub admin on the mailing list: [flathub@lists.freedesktop.org](mailto:flathub@lists.freedesktop.org).

Alright, will do that then.

**Pull request merged**
